# http://docs.travis-ci.com/user/languages/android/
language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - android-29
    - extra-android-m2repository

script: ./gradlew lint test